<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDx2zgam\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDx2zgam/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDx2zgam.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDx2zgam\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDx2zgam\appDevDebugProjectContainer([
    'container.build_hash' => 'Dx2zgam',
    'container.build_id' => 'e91f61e4',
    'container.build_time' => 1638373316,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDx2zgam');
