<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLfntnqo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLfntnqo/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLfntnqo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLfntnqo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLfntnqo\appProdProjectContainer([
    'container.build_hash' => 'Lfntnqo',
    'container.build_id' => '9679b006',
    'container.build_time' => 1638372838,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLfntnqo');
